Refactor the honest scripts (#7)
* Refactor honest script
* Add bash-style function comments
* Add logger supports
* Add a script `share/honest/honest-common.sh` for common variables/functions
* Use pure bash to parse input arguments
* Disable using pager in git diff

diff --git a/libexec/honest b/libexec/honest
--- a/libexec/honest
+++ b/libexec/honest
@@ -23,57 +23,17 @@
 #        If no branch/commit/tag is specified, the latest release(tag) will be used.
 #        With this behavior we can have the simplest usage of honest: `$ honest github:user/proj pip:proj`.
 
-set -E
+# Compatibility to MAC
+[[ "$OSTYPE" == "darwin"* ]] && readlink() { echo $(cd $(dirname "$2") && pwd)/$(basename "$2"); }
+
+SCRIPT_DIR="$(readlink -f "$(dirname "$0")")"
+# Import common functions and variables of honest
+source "$SCRIPT_DIR"/../share/honest/honest-common.sh
+
 # -------- Commonly used variables -------
-HONEST_VERSION="0.0.0"
-RED=''
-GREEN=''
-YELLOW=''
-NC=''
-if [[ -t 1 ]]; then
-  RED='\033[0;31m'
-  GREEN='\033[0;32m'
-  YELLOW='\033[0;33m'
-  NC='\033[0m' # No Color
-fi
-
-# -------- Basic functions --------
-version() {
-  echo "Honest Version $HONEST_VERSION"
-}
-
-usage() {
-  version
-  sed -ne '/^#/!q;s/.\{1,2\}//;1,2d;p' < "$0"
-  [ -z "$1" ] || exit "$1"
-}
-
-die() {
-  echo -e "[${RED}ERROR${NC}] $1"
-  exit 2
-}
-
-info() {
-  echo -e "[${GREEN}INFO${NC}] $1"
-}
-
-resolve_link() {
-  $(type -p greadlink readlink | head -1) "$1"
-}
-
-abs_dirname() {
-  local cwd="$(pwd)"
-  local path="$1"
-
-  while [ -n "$path" ]; do
-    cd "${path%/*}"
-    local name="${path##*/}"
-    path="$(resolve_link "$name" || true)"
-  done
-
-  pwd
-  cd "$cwd"
-}
+HONEST_ROOT="$SCRIPT_DIR"/..
+HONEST_SHARE="$HONEST_ROOT"/share/honest
+export PATH="$HONEST_ROOT/libexec:$PATH"
 
 HONEST_TMP_DIRS=()
 
@@ -85,129 +45,124 @@ push_tmp() {
   HONEST_TMP_DIRS+=("$1")
 }
 
-HONEST_LIBEXEC="$(abs_dirname "$0")"
-export HONEST_PREFIX="$(abs_dirname "$HONEST_LIBEXEC")"
-HONEST_SHARE="$HONEST_PREFIX"/share/honest
-export HONEST_CWD="$(abs_dirname .)"
-export PATH="$HONEST_LIBEXEC:$PATH"
-
-# -------- Option Parsing --------
-parse_options() {
-  getopt --test > /dev/null
-  if [[ $? -ne 4 ]]; then
-    echo "Please install gnu-getopt for Mac: \'brew install gnu-getopt\'"
-    exit 2
-  fi
-  local OPTIONS=hVv:
-  local LONGOPTIONS=help,version
-  PARSED_OPTIONS=$(getopt --options=$OPTIONS --longoptions=$LONGOPTIONS --name "$0" -- "$@")
-  if [[ $? -ne 0 ]]; then
-    exit 2
-  fi
-}
-
-if [[ $# -eq 0 ]]; then
-  usage 1
-fi
-
-parse_options "$@"
-eval set -- "$PARSED_OPTIONS"
-
-while true; do
-  case "$1" in
-    -h|--help)
-      usage
-      exit 0
-      ;;
-    -V|--version)
-      version
-      exit 0
-      ;;
-    -v)
-      PACKAGE_VERSION="$2"
-      shift 2
-      ;;
-    --)
-      shift
-      break
-      ;;
-    *)
-      echo "Hey you forget to handle '$1'!"
-      exit 3
-      ;;
-  esac
-done
-
-if [[ $# -gt 2 ]]; then
-  usage
-  die "Too many arguments (given $#, expected 2)"
-elif [[ $# -ne 2 ]]; then
-  usage
-  die "You must give both <git-url> and <package>!"
-fi
-
-# -------- Download Sources --------
-
+#######################################
+# Download the git repo of a git package.
+# Globals:
+#   None
+# Arguments:
+#   <Package> The package name with format '<vendor>:<author>/<project>[@..]'
+# Returns:
+#   None
+#   Set global variable 'REPO_PATH'
+#######################################
 fetch_repo() {
   if [[ -d "$1" ]]; then
     REPO_PATH="$1"
+    info "Use local repo directory '$1'"
   else
+    info "Fetching the repo '$1'..."
     REPO_PATH="$(honest-clone "$1")"
-    [[ $? != 0 ]] && exit 1
+    [[ $? != 0 ]] && die "Fail on fetching repo '$1'"
     push_tmp "$REPO_PATH"
   fi
 }
 
-in_array() {
-  local e match="$1"
-  shift
-  for e; do [[ "$e" == "$match" ]] && return 0; done
-  return 1
-}
-
-# This function also sets $vendor and $pkg variable
+#######################################
+# Interface function for downloading packages from any vendors.
+# Globals:
+#   None
+# Arguments:
+#   <Vendor>
+#   <Package Name>
+#   [Package version] Optional package version specified by user
+# Returns:
+#   None
+#   Set global variable 'PACKAGE_PATH'
+#######################################
 download_package() {
-  local arg1="$1"
-  vendor=${arg1:0:3}
-  pkg=${arg1:4}
+  local cmd=()
+  local vendor=$1
+  local pkg=$2
+  local ver=$3
 
-  local cmd="honest-$vendor download $pkg"
-  # currently supported package vendors
-  vendors=("gem")
-  in_array "$vendor" "${vendors[@]}"
-  if [[ ${arg1:3:1} != ':' || $? -ne 0 ]]; then
-    usage
-    die "Invalid package name \"$arg1\", see examples."
-  fi
-  if [[ $# -ne 1 ]]; then
-    cmd+=" -v $2"
-  fi
-  PACKAGE_PATH="$($cmd)"
-  if [[ $? -ne 0 ]]; then
-    die "$PACKAGE_PATH"
-  fi
+  # Compile the command
+  cmd+=(honest-$vendor)
+  cmd+=(download $pkg)
+  [[ "$ver" != "" ]] && cmd+=(-v $ver)
+
+  # Execute the command and get the return string
+  info "Downloading the package '$pkg'..."
+  PACKAGE_PATH="$(${cmd[@]})"
+  [[ $? != 0 ]] && die "Fail on running '${cmd[@]}'"
   push_tmp "$PACKAGE_PATH"
 }
 
-download_package "$2" $PACKAGE_VERSION
-fetch_repo "$1"
-
 vendor_diff() {
-  if [[ "$vendor" == 'gem' ]]; then
-    # we have used gem.. so ruby must be installed
-    /usr/bin/env ruby "$HONEST_SHARE"/gem/diff.rb $@
-  else
-    exit 1
-  fi
+  local vendor=$1
+  local pkg=$2
+  local src=$3
+  local tgt=$4
+
+  info "Calculating the honesty..."
+  case "$vendor" in
+    gem )
+      /usr/bin/env ruby "$HONEST_SHARE"/gem/diff.rb $src $tgt
+      ;;
+    * )
+      die "Vendor '$vendor' is currently not supported"
+      ;;
+  esac
   if [[ $? -eq 0 ]]; then
     info "OK, ${YELLOW}$pkg${NC} is ${GREEN}Honest${NC}!"
     clear_tmp_dirs
   else
-    if [[ -t 1 ]]; then
-      (set -x; git diff --no-index --diff-filter=M "$REPO_PATH" "$PACKAGE_PATH"data)
-    fi
+    git --no-pager diff --no-index --diff-filter=M "$REPO_PATH" "$PACKAGE_PATH"/data
     info "NO, ${YELLOW}$pkg${NC} is ${RED}Unhonest${NC}!"
   fi
 }
 
-vendor_diff "$REPO_PATH" "$PACKAGE_PATH"
+main() {
+  local package_ver=""
+  local args=()
+
+  # Parse arguments
+  while [[ "$1" != "" ]]; do
+    case "$1" in
+      -h|--help )
+        usage
+        exit 0
+        ;;
+      -V|--version)
+        version
+        exit 0
+        ;;
+      -v)
+        package_ver="$2"
+        shift 2
+        ;;
+      * )
+        # Exit on argument starting with hyphen "-"
+        [[ "$1" == "-"* ]] && die "Unknown argument $1"
+        # Remember the string type arguments in the array
+        args+=("$1")
+        shift
+        ;;
+    esac
+  done
+
+  # Check # of input arguments after parsing the input arguments
+  [[ ${#args[@]} == 0 ]] && usage && exit 1
+  [[ ${#args[@]} < 2 ]] && die "Both <git-url> and <package> are required!"
+
+  # Check the format and exit on any failure
+  check_package_format "${args[1]}"
+  # Match the first : and extract vendor/pkg name
+  local vendor=${args[1]%%:*}
+  local pkg=${args[1]#*:}
+
+  fetch_repo "${args[0]}"
+  download_package $vendor $pkg $package_ver
+  vendor_diff $vendor $pkg "$REPO_PATH" "$PACKAGE_PATH"
+}
+
+main "$@"
diff --git a/libexec/honest-clone b/libexec/honest-clone
--- a/libexec/honest-clone
+++ b/libexec/honest-clone
@@ -1,83 +1,140 @@
 #!/usr/bin/env bash
 #
-# Usage: honest-clone <git-url>
-
+# Usage: honest-clone <git-url> [--quiet]
+#
+# Options:
+#        --quiet
+#               Hide all the output messages except the name of temp directory
+#
 # Git Url Parameter:
 #        <git-url> can be:
 #               - https://<git org>/<author>/<project>[@<branch|commit|tag>]
 #               - <github|bitbucket|gitlab>:<author>/<project>[@<branch|commit|tag>]
 
-die() {
-  local script_name=`basename "$0"`
-  echo "$script_name: $1"
-  exit 1
-}
+# Compatibility to MAC
+[[ "$OSTYPE" == "darwin"* ]] && readlink() { echo $(cd $(dirname "$2") && pwd)/$(basename "$2"); }
 
-usage() {
-  sed -ne '/^#/!q;s/.\{1,2\}//;1,2d;p' < "$0"
-  [ -z "$1" ] || exit "$1"
-}
+SCRIPT_DIR="$(readlink -f "$(dirname "$0")")"
+QUIET_MODE="0"
+# Import common functions and variables of honest
+source "$SCRIPT_DIR"/../share/honest/honest-common.sh
 
-is_start_with() {
-  [[ "$1" != "$2"* ]] && return 1
-  local str="$1"
-  RESULT="${str:${#2}}"
-}
-
+#######################################
+# Convert <vendor>:<author>/<project>[@..] to git repo format,
+# e.g. [http,https,git]://<vendor's host name>/<author>/<project>[@..]
+# The original string will be returned if:
+#   * failed to convert the format
+#   * the string is already in the repo format
+# Globals:
+#   None
+# Arguments:
+#   <Repo> The repo name with format '<vendor>:<author>/<project>[@..]'
+# Returns:
+#   None
+#   Echos the transformed string
+#######################################
 abbr_form() {
-  # check if url in form <vendor>:<author>/<project>[@..]
-  # if yes, convert it to https://<vendor's url>/<author>/<project>[@..]
-  local url="$1"
-  local vendor_map=("github" "github.com" "bitbucket" "bitbucket.org" "gitlab" "gitlab.com")
-  local n=${#vendor_map[@]}
-  for (( i=0; i<=$n; i+=2 )); do
-    is_start_with "$url" "${vendor_map[$i]}:"
-    if [[ $? -eq 0 ]]; then
-      RESULT="https://${vendor_map[$i+1]}/$RESULT"
-      return 0
-    fi
-  done
-  return 1
-}
+  local vendor=${1%%:*}
+  local repo=${1#*:}
+  local index=$(get_index "$vendor" "${REPO_VENDORS[@]}")
 
-get_tag() {
-  # scan for first '@'
-  # therefore, we don't support urls like 'https://author@github.com/author/proj'
-  local url="$1"
-  local n=${#url}
-  for (( i=0; i<=$n; i++ )); do
-    if [[ ${url:$i:1} == '@' ]]; then
-      REPO=${url:0:$i}
-      TAG=${url:$i+1}
-    fi
-  done
+  if [[ "$1" =~ ^http://*|^https://|^git:// ]]; then
+    # Return the original string if it's already in the git format
+    echo "$1"
+  elif [[ "$index" != "-1" ]]; then
+    # Return the URL if found
+    echo "https://${REPO_VENDORS_HOST[$index]}/$repo"
+  else
+    # Return the original string if fail to parse
+    echo "$1"
+    return 1
+  fi
   return 0
 }
 
-tmp_dir() {
-  # The behavior is a little different betwen Linux and macOS, but it's okay.
-  RESULT="$(TMPDIR=$HONEST_TMPDIR mktemp -d -t honest-XXXXXXXXXX)"
+#######################################
+# Parse the tag string from git URL string which can be
+# 'https://<author>@github.com/<author>/<repo>@v1.0.0'.
+# The tag string will be 'v1.00' in this case.
+# Globals:
+#   None
+# Arguments:
+#   <Repo> The repo name with format 'http(s)://URL[@..]'
+# Returns:
+#   None
+#   Echos the tag string; empty if not found
+#######################################
+get_tag_from_url() {
+  local url=${1#*//} # Remove string before //
+  local proj_path=${url#*/} # Remove string before the first /
+  local tag=$([[ "$proj_path" == *"@"* ]] && echo ${proj_path##*@} || echo "")
+
+  echo $tag
 }
 
-if [[ $# -ne 1 ]]; then
-  usage 1
-fi
-
-REPO="$1"
-abbr_form "$1"
-[[ $? -eq 0 ]] && REPO=$RESULT
-get_tag "$REPO"
-
-tmp_dir; path=$RESULT
-
-go_git() {
+git_clone() {
+  local url="$1"
+  local tag="$2"
+  local path="$3"
+  [[ "$QUIET_MODE" == "1" ]] && local extra_git_args="--quiet"
   set -e
-  git clone "$REPO" "$path"
+  # TODO Use shallow clone or other techniques to improve the speed
+  git clone $extra_git_args "$url" "$path"
   cd $path
-  # if $TAG is not present, checkout to the latest release.
-  TAG="${TAG:-$(git describe --tags `git rev-list --tags --max-count=1 2>/dev/null` 2>/dev/null)}"
-  [[ "$TAG" ]] && git checkout --detach "$TAG"
+  # if $tag is not present, checkout to the latest release.
+  tag="${tag:-$(git describe --tags `git rev-list --tags --max-count=1 2>/dev/null` 2>/dev/null)}"
+  [[ "$tag" != "" ]] && git checkout $extra_git_args --detach "$tag"
   set +e
 }
-go_git 1>/dev/null
-echo $path
+
+main() {
+  local args=()
+
+  # Parse arguments
+  while [[ "$1" != "" ]]; do
+    case "$1" in
+      -h|--help )
+        usage
+        exit 0
+        ;;
+      -V|--version)
+        version
+        exit 0
+        ;;
+      --quite)
+        QUIET_MODE="1"
+        shift
+        ;;
+      * )
+        # Exit on argument starting with hyphen "-"
+        [[ "$1" == "-"* ]] && die "Unknown argument $1"
+        # Remember the string type arguments in the array
+        args+=("$1")
+        shift
+        ;;
+    esac
+  done
+
+  [[ ${#args[@]} == 0 ]] && usage && exit 0
+  local repo="${args[0]}"
+
+  # Verify the input arguments
+  check_repo_format "$repo"
+
+  # Convert the format
+  local url=$(abbr_form "$repo")
+
+  # Retrieve the tag string from url
+  local tag=$(get_tag_from_url $url)
+
+  # Split the string into two parts, repo and tag iff the tag exists in url.
+  [[ "$tag" != "" ]] && url=${url%@*}
+
+  local path=$(get_tmp_dir honest-XXXXXXXXXX)
+  git_clone "$url" "$tag" "$path"
+
+  # Return the path to caller
+  echo "$path"
+}
+
+main "$@"
